// <auto-generated />
using App.Infrastructure.DataAccess.Framework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20180708211506_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("App.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new { CategoryId = 1, CategoryName = "Kid's Shoes" },
                        new { CategoryId = 2, CategoryName = "Men's Shoes" },
                        new { CategoryId = 3, CategoryName = "Women's Shoes" },
                        new { CategoryId = 4, CategoryName = "Kid's Clothing" },
                        new { CategoryId = 5, CategoryName = "Men's Clothing" },
                        new { CategoryId = 6, CategoryName = "Women's Clothing" },
                        new { CategoryId = 7, CategoryName = "Outdoor" },
                        new { CategoryId = 8, CategoryName = "Kitchen" },
                        new { CategoryId = 9, CategoryName = "Toys" }
                    );
                });

            modelBuilder.Entity("App.Domain.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<bool>("Discontinued");

                    b.Property<string>("ProductName");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new { ProductId = 1, CategoryId = 1, Discontinued = false, ProductName = "Nike Runner", UnitPrice = 129.95m },
                        new { ProductId = 2, CategoryId = 1, Discontinued = false, ProductName = "Reebok Runner", UnitPrice = 29.95m },
                        new { ProductId = 3, CategoryId = 1, Discontinued = false, ProductName = "Adidas Runner", UnitPrice = 59.95m },
                        new { ProductId = 4, CategoryId = 1, Discontinued = false, ProductName = "ASIC Runner", UnitPrice = 49.95m },
                        new { ProductId = 5, CategoryId = 1, Discontinued = false, ProductName = "Blue Runner", UnitPrice = 39.95m },
                        new { ProductId = 6, CategoryId = 1, Discontinued = false, ProductName = "Under Runner", UnitPrice = 59.95m }
                    );
                });

            modelBuilder.Entity("App.Domain.Entities.Product", b =>
                {
                    b.HasOne("App.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
